application: zemjotresi
version: 1
runtime: python
api_version: 1

builtins:
  - remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /styles/
  static_dir: template/styles

- url: /images/
  static_dir: template/images

- url: /.*
  script: zemjotresi.py

